---
name: build

"on":
  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      ros_version:
        description: RouterOS Version
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/${{ github.repository }}
          push: ${{ github.event_name == 'workflow_dispatch' }}
          build-args: ROUTEROS_VERSION=${{ inputs.ros_version || env.DEFAULT_VERSION }}
        env:
          DEFAULT_VERSION: "6.48.6"
